name: Build-all Action for LaTeX
description: Compile all matching LaTeX files under one directory, using the same compile rule
author: Junkai DENG, Cheng XU
inputs:
  root_dir:
    description: The root directory where all LaTeX file are located
    required: true
  file_glob:
    description: The filename pattern which are matched with
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root_dir }}
    - ${{ inputs.file_glob }}
branding:
  icon: book
  color: blue
